es = {
    'and': ['y', 1],
    'as': ['como', 2],
    'async': ['asincrónico', 2],
    'assert': ['afirma', 2],
    'await': ['espera', 2],
    'break': ['rompe', 2],
    'class': ['clase', 3],
    'continue': ['sigue', 2],
    'def': ['defina', 3],
    'del': ['borra', 2],
    'elif': ['demássi', 2],
    'else': ['demás', 2],
    'except': ['excepto', 2],
    'exec': ['ejecuta', 4],
    'finally': ['fin', 2],
    'for': ['para', 2],
    'from': ['de', 2],
    'global': ['global', 1],
    'if': ['si', 2],
    'import': ['importa', 2],
    'in': ['en', 1],
    'is': ['es', 1],
    'lambda': ['lambda', 1],
    'nonlocal': ['nolocal', 1],
    'not': ['no', 1],
    'or': ['o', 1],
    'pass': ['pasa', 2],
    'print': ['imprime', 4],
    'raise': ['levanta', 2],
    'return': ['regresa', 2],
    'try': ['prueba', 2],
    'while': ['durante', 2],
    'with': ['con', 2],
    'yield': ['cede', 2],
    'True': ['Cierto', 1],
    'False': ['Falso', 1],
    'None': ['Nada', 2],
    'str': ['secuencia', 5],
    'int': ['entero', 5],
    'float': ['flotante', 5],
    'complex': ['complejo', 5],
    'list': ['lista', 5],
    'tuple': ['tupla', 5],
    'range': ['gama', 4],
    'dict': ['diccionario', 5],
    'set': ['colección', 5],
    'frozenset': ['coleccióninmovilada', 5],
    'bool': ['booleano', 5],
    'bytes': ['bytes', 5],
    'bytearray': ['matrizdebytes', 5],
    'memoryview': ['vistadememoria', 4],
    'NoneType': ['ClaseParaNada', 5]
    }

fr = {
    'and': 'et', 
    'as': 'comme', 
    'async': 'asynchrone', 
    'assert': 'affirme', 
    'await': 'attends', 
    'break': 'fuis', 
    'class': 'catégorie', 
    'continue': 'continue',
    'def': 'définis', 
    'del': 'supprime', 
    'elif': 'dautresi', 
    'else': 'dautre', 
    'except': 'sauf', 
    'exec': 'exécute', 
    'finally': 'enfin', 
    'for': 'pour', 
    'from': 'de', 
    'global': 'mondial', 
    'if': 'si', 
    'import': 'importe', 
    'in': 'dans', 
    'is': 'est', 
    'lambda': 'lambda', 
    'nonlocal': 'paslocale', 
    'not': 'pas', 
    'or': 'soit', 
    'pass': 'passe', 
    'print': 'imprime', 
    'raise': 'soulève', 
    'return': 'rends', 
    'try': 'essaie(essaye)', 
    'while': 'pendant', 
    'with': 'avec', 
    'yield': 'cède', 
    'True': 'Vrai', 
    'False': 'Faux(Fausse)', 
    'None': 'Aucun', 
    'str': 'chaîne', 
    'int': 'entier', 
    'float': 'flottant', 
    'complex': 'complexe', 
    'list': 'liste', 
    'tuple': 'uplet', 
    'range': 'gamme', 
    'dict': 'dictionnaire(dico)', 
    'set': 'collection', 
    'frozenset': 'collectiongelé', 
    'bool': 'booléen', 
    'bytes': 'octets', 
    'bytearray': 'tableaudoctets', 
    'memoryview': 'vuedelamémoire', 
    'NoneType': 'AucunType'
    }
