es = {
    'and': 'y',
    'as': 'como',
    'async': 'asincrónico',
    'assert': 'afirma',
    'await': 'espera',
    'break': 'rompe',
    'class': 'clase',
    'continue': 'sigue',
    'def': 'defina',
    'del': 'borra',
    'elif': 'si_no_si',
    'else': 'si_no',
    'except': 'excepto',
    'exec': 'ejecuta',
    'finally': 'fin',
    'for': 'para',
    'from': 'de',
    'global': 'global',
    'if': 'si',
    'import': 'importa',
    'in': 'en',
    'is': 'es',
    'lambda': 'lambda',
    'nonlocal': 'nolocal',
    'not': 'no',
    'or': 'o',
    'pass': 'pasa',
    'print': 'imprime',
    'raise': 'levanta',
    'return': 'regresa',
    'try': 'prueba',
    'while': 'durante',
    'with': 'con',
    'yield': 'cede',
    'True': 'Cierto',
    'False': 'Falso',
    'None': 'Nada',
    'str': 'secuencia',
    'int': 'entero',
    'float': 'flotante',
    'complex': 'complejo',
    'list': 'lista',
    'tuple': 'tupla',
    'range': 'gama',
    'dict': 'diccionario',
    'set': 'colección',
    'frozenset': 'coleccióninmovilada',
    'bool': 'booleano',
    'bytes': 'bytes',
    'bytearray': 'matrizdebytes',
    'memoryview': 'vistadememoria',
    'NoneType': 'ClaseParaNada'
    }

fr = {
    'and': 'et', 
    'as': 'comme', 
    'async': 'asynchrone', 
    'assert': 'affirme', 
    'await': 'attends', 
    'break': 'romps', 
    'class': 'classe', 
    'continue': 'continue',
    'def': 'définis', 
    'del': 'supprime', 
    'elif': 'sinon_si', 
    'else': 'sinon', 
    'except': 'sauf', 
    'exec': 'exécute', 
    'finally': 'enfin', 
    'for': 'pour', 
    'from': 'de', 
    'global': 'déclares_global', 
    'if': 'si', 
    'import': 'importer', 
    'in': 'dans', 
    'is': 'est', 
    'lambda': 'lambda', 
    'nonlocal': 'non_local', 
    'not': 'non', 
    'or': 'ou', 
    'pass': 'passe', 
    'print': 'imprimes', 
    'raise': 'lève', 
    'return': 'retournes', 
    'try': 'essaie', 
    'while': 'pendant', 
    'with': 'avec', 
    'yield': 'rends', 
    'True': 'Vrai', 
    'False': 'Faux', 
    'None': 'Aucun', 
    'str': 'chaîne', 
    'int': 'entier', 
    'float': 'flottant', 
    'complex': 'complexe', 
    'list': 'liste', 
    'tuple': 'uplet', 
    'range': 'gamme', 
    'dict': 'dictionnaire', 
    'set': 'collection', 
    'frozenset': 'collectiongelé', 
    'bool': 'booléen', 
    'bytes': 'octets', 
    'bytearray': 'tableaudoctets', 
    'memoryview': 'vuedelamémoire', 
    'NoneType': 'AucunType'
    }

zh = {    #rename when possible: zh-CN
    'and': '和',
    'as': '如同',
    'async': '不同时的',
    'assert': '断言',
    'await': '等待',
    'break': '断', 
    'class': '类',
    'continue': '继续',
    'def': '确定',
    'del': '删除',
    'elif': '否则如果',
    'else':  '否则',
    'except': '例外',
    'exec': '执行',
    'finally': '终于',
    'for': '对于',
    'from': '由',
    'global': '全球',
    'if': '如果',
    'import': '输入',
    'in': '里',
    'is': '是',
    'lambda': '拉姆达',
    'nonlocal': '非本地的',
    'not': '不',
    'or': '或',
    'pass': '经过',
    'print': '打印',
    'raise': '引发错误',
    'return': '归还',
    'try': '试图',
    'while': '当时',
    'with': '有',
    'yield': '产生',
    'True': '确实',
    'False': '假',
    'None': '无',
    'str': '序',
    'int': '整数',
    'float': '小数',
    'complex': '复数',
    'list': '表',
    'tuple': '元组',
    'range': '范围',
    'dict': '词典',
    'set': '集',
    'frozenset': '冻集',
    'bool': '布尔值',
    'bytes': '字节',
    'bytearray': '字节数组',
    'memoryview': '内存视图',
    'NoneType': '无类型'
    }

hi = {
    'and': 'और', 
    'as': 'जैसा',
    'async': 'अतुल्यकालिक',
    'assert': 'ज़ोर', 
    'await': 'इंतजार', 
    'break': 'तोड़ना', 
    'class': 'श्रेणी',
    'continue': 'बनाए रखना',
    'def': 'परिभाषित करना',
    'del': 'हटाना',
    'elif': 'अन्यथा यदि',
    'else': 'अन्यथा',
    'except': 'के अलावा',
    'exec': 'तामील करना',
    'finally': 'आखिरकार',
    'for': 'के लिए',
    'from': 'से',
    'global': 'वैश्विक', 
    'if': 'अगर',
    'import': 'आयात करना',
    'in': 'अंदर',
    'is': 'है',
    'lambda': 'लैम्ब्डा',
    'nonlocal': 'गैर स्थानीय',
    'not': 'नहीं',
    'or': 'या',
    'pass': 'उत्तीर्ण', 
    'print': 'प्रिंट',
    'raise': 'बढ़ाना',
    'return': 'लौटाना',
    'try': 'प्रयास करना', 
    'while': 'जब',
    'with': 'साथ' ,
    'yield': 'मान लेना',  
    'True': 'सत्य' ,
    'False': 'ग़लत', 
    'None': 'लेश मात्र नहीं',
    'str': 'डोरी',
    'int': 'पूर्णांक',
    'float': 'वायु पर तैरना',
    'complex': 'जटिल',
    'list': 'सूचीबद्ध करना',
    'tuple': 'टपल',
    'range': 'पंक्ति से रखना', 
    'dict': 'शब्दकोष',
    'set': 'लगाना',
    'frozenset': 'जमे हुए सेट',
    'bool': 'बूलियन',
    'bytes': 'बाइट्स', 
    'bytearray': 'बाइट सरणी',
    'memoryview': 'स्मृति दर्शन',
    'NoneType': 'कोई भी प्रकार नहीं' 
    }
